# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Diagnósticos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmDiagnostico(object):
    def setupUi(self, frmDiagnostico):
        frmDiagnostico.setObjectName("frmDiagnostico")
        frmDiagnostico.resize(261, 232)
        self.listDiagnosticos = QtWidgets.QListWidget(frmDiagnostico)
        self.listDiagnosticos.setGeometry(QtCore.QRect(20, 50, 221, 111))
        self.listDiagnosticos.setObjectName("listDiagnosticos")
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        self.lblDiagnostico = QtWidgets.QLabel(frmDiagnostico)
        self.lblDiagnostico.setGeometry(QtCore.QRect(20, 20, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDiagnostico.setFont(font)
        self.lblDiagnostico.setObjectName("lblDiagnostico")
        self.lblResultado = QtWidgets.QLabel(frmDiagnostico)
        self.lblResultado.setGeometry(QtCore.QRect(20, 190, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblResultado.setFont(font)
        self.lblResultado.setObjectName("lblResultado")
        self.lblResultado2 = QtWidgets.QLabel(frmDiagnostico)
        self.lblResultado2.setGeometry(QtCore.QRect(90, 190, 151, 16))
        self.lblResultado2.setText("")
        self.lblResultado2.setObjectName("lblResultado2")

        self.retranslateUi(frmDiagnostico)
        QtCore.QMetaObject.connectSlotsByName(frmDiagnostico)

    def retranslateUi(self, frmDiagnostico):
        _translate = QtCore.QCoreApplication.translate
        frmDiagnostico.setWindowTitle(_translate("frmDiagnostico", "Diagnósticos"))
        __sortingEnabled = self.listDiagnosticos.isSortingEnabled()
        self.listDiagnosticos.setSortingEnabled(False)
        item = self.listDiagnosticos.item(0)
        item.setText(_translate("frmDiagnostico", "Rayos X: 5 €"))
        item = self.listDiagnosticos.item(1)
        item.setText(_translate("frmDiagnostico", "Nivel de Azúcar: 3 €"))
        item = self.listDiagnosticos.item(2)
        item.setText(_translate("frmDiagnostico", "Prueba de Hemoglobina: 7 €"))
        item = self.listDiagnosticos.item(3)
        item.setText(_translate("frmDiagnostico", "Análisis de Orina: 8 €"))
        item = self.listDiagnosticos.item(4)
        item.setText(_translate("frmDiagnostico", "Análisis de Sangre: 10 €"))
        self.listDiagnosticos.setSortingEnabled(__sortingEnabled)
        self.lblDiagnostico.setText(_translate("frmDiagnostico", "Seleccione el diagnóstico:"))
        self.lblResultado.setText(_translate("frmDiagnostico", "Resultado:"))
