# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RelojDigital.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmRelojDigital(object):
    def setupUi(self, frmRelojDigital):
        frmRelojDigital.setObjectName("frmRelojDigital")
        frmRelojDigital.resize(232, 112)
        self.lcdReloj = QtWidgets.QLCDNumber(frmRelojDigital)
        self.lcdReloj.setGeometry(QtCore.QRect(20, 20, 191, 71))
        self.lcdReloj.setObjectName("lcdReloj")

        self.retranslateUi(frmRelojDigital)
        QtCore.QMetaObject.connectSlotsByName(frmRelojDigital)

    def retranslateUi(self, frmRelojDigital):
        _translate = QtCore.QCoreApplication.translate
        frmRelojDigital.setWindowTitle(_translate("frmRelojDigital", "Reloj Digital"))
