# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConsultaDatosProductos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmConsultaDatos(object):
    def setupUi(self, frmConsultaDatos):
        frmConsultaDatos.setObjectName("frmConsultaDatos")
        frmConsultaDatos.resize(441, 380)
        frmConsultaDatos.setStyleSheet("QPushButton#btnConectar{border-radius: 0px}\n"
"QHeaderView::section{background-color:#c5c5c5; font-weight: bold}")
        self.lblBBDD = QtWidgets.QLabel(frmConsultaDatos)
        self.lblBBDD.setGeometry(QtCore.QRect(40, 50, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBBDD.setFont(font)
        self.lblBBDD.setObjectName("lblBBDD")
        self.lblTabla = QtWidgets.QLabel(frmConsultaDatos)
        self.lblTabla.setGeometry(QtCore.QRect(40, 90, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTabla.setFont(font)
        self.lblTabla.setObjectName("lblTabla")
        self.txtBBDD = QtWidgets.QLineEdit(frmConsultaDatos)
        self.txtBBDD.setGeometry(QtCore.QRect(180, 50, 171, 20))
        self.txtBBDD.setObjectName("txtBBDD")
        self.txtTabla = QtWidgets.QLineEdit(frmConsultaDatos)
        self.txtTabla.setGeometry(QtCore.QRect(180, 89, 171, 20))
        self.txtTabla.setObjectName("txtTabla")
        self.groupBox = QtWidgets.QGroupBox(frmConsultaDatos)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 401, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btnConsultar = QtWidgets.QPushButton(self.groupBox)
        self.btnConsultar.setGeometry(QtCore.QRect(350, 63, 32, 32))
        self.btnConsultar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("consulta.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConsultar.setIcon(icon)
        self.btnConsultar.setIconSize(QtCore.QSize(32, 32))
        self.btnConsultar.setObjectName("btnConsultar")
        self.btnConectar = QtWidgets.QPushButton(self.groupBox)
        self.btnConectar.setGeometry(QtCore.QRect(350, 24, 32, 32))
        self.btnConectar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("conexion.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConectar.setIcon(icon1)
        self.btnConectar.setIconSize(QtCore.QSize(32, 32))
        self.btnConectar.setObjectName("btnConectar")
        self.tabDatosProductos = QtWidgets.QTableWidget(frmConsultaDatos)
        self.tabDatosProductos.setGeometry(QtCore.QRect(20, 150, 401, 211))
        self.tabDatosProductos.setAlternatingRowColors(True)
        self.tabDatosProductos.setRowCount(6)
        self.tabDatosProductos.setColumnCount(2)
        self.tabDatosProductos.setObjectName("tabDatosProductos")
        self.groupBox.raise_()
        self.lblBBDD.raise_()
        self.lblTabla.raise_()
        self.txtBBDD.raise_()
        self.txtTabla.raise_()
        self.tabDatosProductos.raise_()

        self.retranslateUi(frmConsultaDatos)
        QtCore.QMetaObject.connectSlotsByName(frmConsultaDatos)
        frmConsultaDatos.setTabOrder(self.txtBBDD, self.btnConectar)
        frmConsultaDatos.setTabOrder(self.btnConectar, self.txtTabla)
        frmConsultaDatos.setTabOrder(self.txtTabla, self.btnConsultar)
        frmConsultaDatos.setTabOrder(self.btnConsultar, self.tabDatosProductos)

    def retranslateUi(self, frmConsultaDatos):
        _translate = QtCore.QCoreApplication.translate
        frmConsultaDatos.setWindowTitle(_translate("frmConsultaDatos", "Consulta y Visualización de Datos"))
        self.lblBBDD.setText(_translate("frmConsultaDatos", "Nombre Base de Datos:"))
        self.lblTabla.setText(_translate("frmConsultaDatos", "Nombre Tabla:"))
        self.groupBox.setTitle(_translate("frmConsultaDatos", " Consulta "))
        self.btnConsultar.setToolTip(_translate("frmConsultaDatos", "Consultar Datos"))
        self.btnConectar.setToolTip(_translate("frmConsultaDatos", "Conectar BBDD"))
