# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreadorBBDD.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmCrearBBDD(object):
    def setupUi(self, frmCrearBBDD):
        frmCrearBBDD.setObjectName("frmCrearBBDD")
        frmCrearBBDD.resize(441, 153)
        self.lblNombreBBDD = QtWidgets.QLabel(frmCrearBBDD)
        self.lblNombreBBDD.setGeometry(QtCore.QRect(21, 32, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNombreBBDD.setFont(font)
        self.lblNombreBBDD.setObjectName("lblNombreBBDD")
        self.lblInformacion = QtWidgets.QLabel(frmCrearBBDD)
        self.lblInformacion.setGeometry(QtCore.QRect(20, 109, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblInformacion.setFont(font)
        self.lblInformacion.setObjectName("lblInformacion")
        self.txtNombreBBDD = QtWidgets.QLineEdit(frmCrearBBDD)
        self.txtNombreBBDD.setGeometry(QtCore.QRect(160, 30, 261, 20))
        self.txtNombreBBDD.setObjectName("txtNombreBBDD")
        self.txtInformacion = QtWidgets.QLineEdit(frmCrearBBDD)
        self.txtInformacion.setGeometry(QtCore.QRect(100, 110, 321, 20))
        self.txtInformacion.setReadOnly(True)
        self.txtInformacion.setObjectName("txtInformacion")
        self.btnCrearBBDD = QtWidgets.QPushButton(frmCrearBBDD)
        self.btnCrearBBDD.setGeometry(QtCore.QRect(270, 60, 151, 23))
        self.btnCrearBBDD.setObjectName("btnCrearBBDD")

        self.retranslateUi(frmCrearBBDD)
        QtCore.QMetaObject.connectSlotsByName(frmCrearBBDD)
        frmCrearBBDD.setTabOrder(self.txtNombreBBDD, self.btnCrearBBDD)
        frmCrearBBDD.setTabOrder(self.btnCrearBBDD, self.txtInformacion)

    def retranslateUi(self, frmCrearBBDD):
        _translate = QtCore.QCoreApplication.translate
        frmCrearBBDD.setWindowTitle(_translate("frmCrearBBDD", "Creación Bases de Datos"))
        self.lblNombreBBDD.setText(_translate("frmCrearBBDD", "Nombre Base de datos:"))
        self.lblInformacion.setText(_translate("frmCrearBBDD", "Información:"))
        self.btnCrearBBDD.setText(_translate("frmCrearBBDD", "Crear Base de Datos"))
