# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoVuelo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaVuelo(object):
    def setupUi(self, ventanaVuelo):
        ventanaVuelo.setObjectName("ventanaVuelo")
        ventanaVuelo.resize(350, 191)
        self.lblTitulo = QtWidgets.QLabel(ventanaVuelo)
        self.lblTitulo.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblResultado = QtWidgets.QLabel(ventanaVuelo)
        self.lblResultado.setGeometry(QtCore.QRect(20, 160, 241, 16))
        self.lblResultado.setObjectName("lblResultado")
        self.rbnPrimera = QtWidgets.QRadioButton(ventanaVuelo)
        self.rbnPrimera.setGeometry(QtCore.QRect(20, 60, 101, 17))
        self.rbnPrimera.setObjectName("rbnPrimera")
        self.rbnNegocios = QtWidgets.QRadioButton(ventanaVuelo)
        self.rbnNegocios.setGeometry(QtCore.QRect(20, 90, 101, 17))
        self.rbnNegocios.setObjectName("rbnNegocios")
        self.rbnEconomica = QtWidgets.QRadioButton(ventanaVuelo)
        self.rbnEconomica.setGeometry(QtCore.QRect(20, 120, 101, 17))
        self.rbnEconomica.setObjectName("rbnEconomica")

        self.retranslateUi(ventanaVuelo)
        QtCore.QMetaObject.connectSlotsByName(ventanaVuelo)

    def retranslateUi(self, ventanaVuelo):
        _translate = QtCore.QCoreApplication.translate
        ventanaVuelo.setWindowTitle(_translate("ventanaVuelo", "Vuelo"))
        self.lblTitulo.setText(_translate("ventanaVuelo", "Escoja la clase del vuelo:"))
        self.lblResultado.setText(_translate("ventanaVuelo", "<<Muestra clase seleccionada y valor asociado>>"))
        self.rbnPrimera.setText(_translate("ventanaVuelo", "Primera Clase"))
        self.rbnNegocios.setText(_translate("ventanaVuelo", "Clase Negocios"))
        self.rbnEconomica.setText(_translate("ventanaVuelo", "Clase Economica"))
