# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmLabel(object):
    def setupUi(self, frmLabel):
        frmLabel.setObjectName("frmLabel")
        frmLabel.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(frmLabel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        frmLabel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmLabel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        frmLabel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmLabel)
        self.statusbar.setObjectName("statusbar")
        frmLabel.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(frmLabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        frmLabel.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNuevoUsuario = QtWidgets.QAction(frmLabel)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/añadir.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevoUsuario.setIcon(icon)
        self.actionNuevoUsuario.setObjectName("actionNuevoUsuario")
        self.actionModificarUsuario = QtWidgets.QAction(frmLabel)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/modificar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModificarUsuario.setIcon(icon1)
        self.actionModificarUsuario.setObjectName("actionModificarUsuario")
        self.actionNuevo = QtWidgets.QAction(frmLabel)
        self.actionNuevo.setObjectName("actionNuevo")
        self.menuArchivo.addAction(self.actionNuevo)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.toolBar.addAction(self.actionNuevoUsuario)
        self.toolBar.addAction(self.actionModificarUsuario)
        self.toolBar.addSeparator()

        self.retranslateUi(frmLabel)
        QtCore.QMetaObject.connectSlotsByName(frmLabel)

    def retranslateUi(self, frmLabel):
        _translate = QtCore.QCoreApplication.translate
        frmLabel.setWindowTitle(_translate("frmLabel", "MainWindow"))
        self.label.setText(_translate("frmLabel", "TextLabel"))
        self.menuArchivo.setTitle(_translate("frmLabel", "Archivo"))
        self.toolBar.setWindowTitle(_translate("frmLabel", "toolBar"))
        self.actionNuevoUsuario.setText(_translate("frmLabel", "NuevoUsuario"))
        self.actionNuevoUsuario.setShortcut(_translate("frmLabel", "Shift+N"))
        self.actionModificarUsuario.setText(_translate("frmLabel", "ModificarUsuario"))
        self.actionModificarUsuario.setShortcut(_translate("frmLabel", "Shift+M"))
        self.actionNuevo.setText(_translate("frmLabel", "Nuevo"))
