# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CopiarPegar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmCopiarPegar(object):
    def setupUi(self, frmCopiarPegar):
        frmCopiarPegar.setObjectName("frmCopiarPegar")
        frmCopiarPegar.resize(251, 211)
        self.txtTexto1 = QtWidgets.QLineEdit(frmCopiarPegar)
        self.txtTexto1.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.txtTexto1.setObjectName("txtTexto1")
        self.txtTexto2 = QtWidgets.QLineEdit(frmCopiarPegar)
        self.txtTexto2.setGeometry(QtCore.QRect(30, 160, 191, 20))
        self.txtTexto2.setObjectName("txtTexto2")
        self.btnCopiar = QtWidgets.QPushButton(frmCopiarPegar)
        self.btnCopiar.setGeometry(QtCore.QRect(90, 80, 75, 23))
        self.btnCopiar.setObjectName("btnCopiar")
        self.btnPegar = QtWidgets.QPushButton(frmCopiarPegar)
        self.btnPegar.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.btnPegar.setObjectName("btnPegar")

        self.retranslateUi(frmCopiarPegar)
        self.btnCopiar.pressed.connect(self.txtTexto1.selectAll)
        self.btnCopiar.released.connect(self.txtTexto1.copy)
        self.btnPegar.released.connect(self.txtTexto2.clear)
        self.btnPegar.released.connect(self.txtTexto2.paste)
        QtCore.QMetaObject.connectSlotsByName(frmCopiarPegar)

    def retranslateUi(self, frmCopiarPegar):
        _translate = QtCore.QCoreApplication.translate
        frmCopiarPegar.setWindowTitle(_translate("frmCopiarPegar", "Copiar y Pegar Texto"))
        self.btnCopiar.setText(_translate("frmCopiarPegar", "Copiar"))
        self.btnPegar.setText(_translate("frmCopiarPegar", "Pegar"))
