# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BarraMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class winEditorGrafico(object):
    def setupUi(self, winEditorGrafico):
        winEditorGrafico.setObjectName("winEditorGrafico")
        winEditorGrafico.resize(552, 398)
        self.centralwidget = QtWidgets.QWidget(winEditorGrafico)
        self.centralwidget.setObjectName("centralwidget")
        self.lblEstado = QtWidgets.QLabel(self.centralwidget)
        self.lblEstado.setGeometry(QtCore.QRect(10, 20, 351, 16))
        self.lblEstado.setText("")
        self.lblEstado.setObjectName("lblEstado")
        winEditorGrafico.setCentralWidget(self.centralwidget)
        self.mbrPrincipal = QtWidgets.QMenuBar(winEditorGrafico)
        self.mbrPrincipal.setGeometry(QtCore.QRect(0, 0, 552, 21))
        self.mbrPrincipal.setObjectName("mbrPrincipal")
        self.mnuDibujar = QtWidgets.QMenu(self.mbrPrincipal)
        self.mnuDibujar.setObjectName("mnuDibujar")
        self.mnuPropiedades = QtWidgets.QMenu(self.mnuDibujar)
        self.mnuPropiedades.setObjectName("mnuPropiedades")
        self.mnuEditar = QtWidgets.QMenu(self.mbrPrincipal)
        self.mnuEditar.setObjectName("mnuEditar")
        winEditorGrafico.setMenuBar(self.mbrPrincipal)
        self.statusbar = QtWidgets.QStatusBar(winEditorGrafico)
        self.statusbar.setObjectName("statusbar")
        winEditorGrafico.setStatusBar(self.statusbar)
        self.mniCopiar = QtWidgets.QAction(winEditorGrafico)
        self.mniCopiar.setObjectName("mniCopiar")
        self.mniCortar = QtWidgets.QAction(winEditorGrafico)
        self.mniCortar.setObjectName("mniCortar")
        self.mniPegar = QtWidgets.QAction(winEditorGrafico)
        self.mniPegar.setObjectName("mniPegar")
        self.mniDibujar_circulo = QtWidgets.QAction(winEditorGrafico)
        self.mniDibujar_circulo.setObjectName("mniDibujar_circulo")
        self.mniDibujar_rectangulo = QtWidgets.QAction(winEditorGrafico)
        self.mniDibujar_rectangulo.setObjectName("mniDibujar_rectangulo")
        self.mniDibujar_linea = QtWidgets.QAction(winEditorGrafico)
        self.mniDibujar_linea.setObjectName("mniDibujar_linea")
        self.mniEstablecer_contrasena = QtWidgets.QAction(winEditorGrafico)
        self.mniEstablecer_contrasena.setObjectName("mniEstablecer_contrasena")
        self.mniConfigurar_pagina = QtWidgets.QAction(winEditorGrafico)
        self.mniConfigurar_pagina.setObjectName("mniConfigurar_pagina")
        self.mnuPropiedades.addAction(self.mniEstablecer_contrasena)
        self.mnuPropiedades.addAction(self.mniConfigurar_pagina)
        self.mnuDibujar.addAction(self.mniDibujar_circulo)
        self.mnuDibujar.addAction(self.mniDibujar_rectangulo)
        self.mnuDibujar.addAction(self.mniDibujar_linea)
        self.mnuDibujar.addSeparator()
        self.mnuDibujar.addSeparator()
        self.mnuDibujar.addAction(self.mnuPropiedades.menuAction())
        self.mnuEditar.addAction(self.mniCopiar)
        self.mnuEditar.addAction(self.mniCortar)
        self.mnuEditar.addAction(self.mniPegar)
        self.mbrPrincipal.addAction(self.mnuDibujar.menuAction())
        self.mbrPrincipal.addAction(self.mnuEditar.menuAction())

        self.retranslateUi(winEditorGrafico)
        QtCore.QMetaObject.connectSlotsByName(winEditorGrafico)

    def retranslateUi(self, winEditorGrafico):
        _translate = QtCore.QCoreApplication.translate
        winEditorGrafico.setWindowTitle(_translate("winEditorGrafico", "Editor Gráfico"))
        self.mnuDibujar.setTitle(_translate("winEditorGrafico", "Dibujar"))
        self.mnuPropiedades.setTitle(_translate("winEditorGrafico", "Propiedades"))
        self.mnuEditar.setTitle(_translate("winEditorGrafico", "Editar"))
        self.mniCopiar.setText(_translate("winEditorGrafico", "Copiar"))
        self.mniCopiar.setShortcut(_translate("winEditorGrafico", "Ctrl+C"))
        self.mniCortar.setText(_translate("winEditorGrafico", "Cortar"))
        self.mniCortar.setShortcut(_translate("winEditorGrafico", "Ctrl+X"))
        self.mniPegar.setText(_translate("winEditorGrafico", "Pegar"))
        self.mniPegar.setShortcut(_translate("winEditorGrafico", "Ctrl+V"))
        self.mniDibujar_circulo.setText(_translate("winEditorGrafico", "Dibujar &círculo"))
        self.mniDibujar_circulo.setShortcut(_translate("winEditorGrafico", "Shift+C"))
        self.mniDibujar_rectangulo.setText(_translate("winEditorGrafico", "Dibujar &rectángulo"))
        self.mniDibujar_rectangulo.setShortcut(_translate("winEditorGrafico", "Ctrl+R"))
        self.mniDibujar_linea.setText(_translate("winEditorGrafico", "Dibujar &línea"))
        self.mniDibujar_linea.setShortcut(_translate("winEditorGrafico", "Ctrl+L"))
        self.mniEstablecer_contrasena.setText(_translate("winEditorGrafico", "Establecer contraseña"))
        self.mniEstablecer_contrasena.setShortcut(_translate("winEditorGrafico", "Ctrl+T"))
        self.mniConfigurar_pagina.setText(_translate("winEditorGrafico", "Configurar página"))
        self.mniConfigurar_pagina.setShortcut(_translate("winEditorGrafico", "Ctrl+P"))
