# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaSubventanas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1131, 631))
        self.mdiArea.setObjectName("mdiArea")
        self.winPrimeraVent = QtWidgets.QWidget()
        self.winPrimeraVent.setObjectName("winPrimeraVent")
        self.lblTitulo1 = QtWidgets.QLabel(self.winPrimeraVent)
        self.lblTitulo1.setGeometry(QtCore.QRect(30, 30, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo1.setFont(font)
        self.lblTitulo1.setObjectName("lblTitulo1")
        self.winSegundaVent = QtWidgets.QWidget()
        self.winSegundaVent.setObjectName("winSegundaVent")
        self.lblTitulo2 = QtWidgets.QLabel(self.winSegundaVent)
        self.lblTitulo2.setGeometry(QtCore.QRect(30, 30, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo2.setFont(font)
        self.lblTitulo2.setObjectName("lblTitulo2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.mbrPrincipal = QtWidgets.QMenuBar(MainWindow)
        self.mbrPrincipal.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.mbrPrincipal.setObjectName("mbrPrincipal")
        self.mnuVistas = QtWidgets.QMenu(self.mbrPrincipal)
        self.mnuVistas.setObjectName("mnuVistas")
        MainWindow.setMenuBar(self.mbrPrincipal)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mniPestana = QtWidgets.QAction(MainWindow)
        self.mniPestana.setObjectName("mniPestana")
        self.mniCascada = QtWidgets.QAction(MainWindow)
        self.mniCascada.setObjectName("mniCascada")
        self.mniCuadricula = QtWidgets.QAction(MainWindow)
        self.mniCuadricula.setObjectName("mniCuadricula")
        self.mniSubVentanas = QtWidgets.QAction(MainWindow)
        self.mniSubVentanas.setObjectName("mniSubVentanas")
        self.mnuVistas.addAction(self.mniPestana)
        self.mnuVistas.addAction(self.mniCascada)
        self.mnuVistas.addAction(self.mniCuadricula)
        self.mnuVistas.addAction(self.mniSubVentanas)
        self.mbrPrincipal.addAction(self.mnuVistas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana Principal"))
        self.winPrimeraVent.setWindowTitle(_translate("MainWindow", "Primera Subventana"))
        self.lblTitulo1.setText(_translate("MainWindow", "Primera Subventana"))
        self.winSegundaVent.setWindowTitle(_translate("MainWindow", "Segunda Subventana"))
        self.lblTitulo2.setText(_translate("MainWindow", "Segunda Subventana"))
        self.mnuVistas.setTitle(_translate("MainWindow", "Vistas"))
        self.mniPestana.setText(_translate("MainWindow", "Pestañas"))
        self.mniCascada.setText(_translate("MainWindow", "Cascada"))
        self.mniCuadricula.setText(_translate("MainWindow", "Cuadricula"))
        self.mniSubVentanas.setText(_translate("MainWindow", "Sub Ventanas"))
