# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaSubventanas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmContenedorVentanas(object):
    def setupUi(self, frmContenedorVentanas):
        frmContenedorVentanas.setObjectName("frmContenedorVentanas")
        frmContenedorVentanas.resize(640, 480)
        frmContenedorVentanas.setMinimumSize(QtCore.QSize(640, 480))
        frmContenedorVentanas.setMaximumSize(QtCore.QSize(640, 480))
        self.wdg_principal = QtWidgets.QWidget(frmContenedorVentanas)
        self.wdg_principal.setObjectName("wdg_principal")
        self.mdiArea = QtWidgets.QMdiArea(self.wdg_principal)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1131, 631))
        self.mdiArea.setObjectName("mdiArea")
        self.winPrimeraVent = QtWidgets.QWidget()
        self.winPrimeraVent.setObjectName("winPrimeraVent")
        self.lblTitulo1 = QtWidgets.QLabel(self.winPrimeraVent)
        self.lblTitulo1.setGeometry(QtCore.QRect(30, 30, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo1.setFont(font)
        self.lblTitulo1.setObjectName("lblTitulo1")
        self.winSegundaVent = QtWidgets.QWidget()
        self.winSegundaVent.setObjectName("winSegundaVent")
        self.lblTitulo2 = QtWidgets.QLabel(self.winSegundaVent)
        self.lblTitulo2.setGeometry(QtCore.QRect(30, 30, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo2.setFont(font)
        self.lblTitulo2.setObjectName("lblTitulo2")
        frmContenedorVentanas.setCentralWidget(self.wdg_principal)
        self.mbrPrincipal = QtWidgets.QMenuBar(frmContenedorVentanas)
        self.mbrPrincipal.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.mbrPrincipal.setObjectName("mbrPrincipal")
        self.mnuVistas = QtWidgets.QMenu(self.mbrPrincipal)
        self.mnuVistas.setObjectName("mnuVistas")
        frmContenedorVentanas.setMenuBar(self.mbrPrincipal)
        self.statusbar = QtWidgets.QStatusBar(frmContenedorVentanas)
        self.statusbar.setObjectName("statusbar")
        frmContenedorVentanas.setStatusBar(self.statusbar)
        self.mniPestana = QtWidgets.QAction(frmContenedorVentanas)
        self.mniPestana.setObjectName("mniPestana")
        self.mniCascada = QtWidgets.QAction(frmContenedorVentanas)
        self.mniCascada.setObjectName("mniCascada")
        self.mniCuadricula = QtWidgets.QAction(frmContenedorVentanas)
        self.mniCuadricula.setObjectName("mniCuadricula")
        self.mniSubVentanas = QtWidgets.QAction(frmContenedorVentanas)
        self.mniSubVentanas.setObjectName("mniSubVentanas")
        self.mnuVistas.addAction(self.mniPestana)
        self.mnuVistas.addAction(self.mniCascada)
        self.mnuVistas.addAction(self.mniCuadricula)
        self.mnuVistas.addAction(self.mniSubVentanas)
        self.mbrPrincipal.addAction(self.mnuVistas.menuAction())

        self.retranslateUi(frmContenedorVentanas)
        QtCore.QMetaObject.connectSlotsByName(frmContenedorVentanas)

    def retranslateUi(self, frmContenedorVentanas):
        _translate = QtCore.QCoreApplication.translate
        frmContenedorVentanas.setWindowTitle(_translate("frmContenedorVentanas", "Ventana Principal"))
        self.winPrimeraVent.setWindowTitle(_translate("frmContenedorVentanas", "Primera Subventana"))
        self.lblTitulo1.setText(_translate("frmContenedorVentanas", "Primera Subventana"))
        self.winSegundaVent.setWindowTitle(_translate("frmContenedorVentanas", "Segunda Subventana"))
        self.lblTitulo2.setText(_translate("frmContenedorVentanas", "Segunda Subventana"))
        self.mnuVistas.setTitle(_translate("frmContenedorVentanas", "Vistas"))
        self.mniPestana.setText(_translate("frmContenedorVentanas", "Pestañas"))
        self.mniCascada.setText(_translate("frmContenedorVentanas", "Cascada"))
        self.mniCuadricula.setText(_translate("frmContenedorVentanas", "Cuadricula"))
        self.mniSubVentanas.setText(_translate("frmContenedorVentanas", "Sub Ventanas"))
