# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeleccionColores.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmSeleccionColor(object):
    def setupUi(self, frmSeleccionColor):
        frmSeleccionColor.setObjectName("frmSeleccionColor")
        frmSeleccionColor.resize(292, 143)
        frmSeleccionColor.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnSeleccionColor = QtWidgets.QPushButton(frmSeleccionColor)
        self.btnSeleccionColor.setGeometry(QtCore.QRect(20, 40, 131, 23))
        self.btnSeleccionColor.setObjectName("btnSeleccionColor")
        self.lblColor = QtWidgets.QLabel(frmSeleccionColor)
        self.lblColor.setGeometry(QtCore.QRect(19, 98, 150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblColor.setFont(font)
        self.lblColor.setObjectName("lblColor")
        self.txtColor = QtWidgets.QLineEdit(frmSeleccionColor)
        self.txtColor.setGeometry(QtCore.QRect(170, 100, 91, 20))
        self.txtColor.setObjectName("txtColor")
        self.txtColor.setReadOnly(True)
        self.frameColor = QtWidgets.QFrame(frmSeleccionColor)
        self.frameColor.setGeometry(QtCore.QRect(180, 20, 71, 61))
        self.frameColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColor.setObjectName("frameColor")

        self.retranslateUi(frmSeleccionColor)
        QtCore.QMetaObject.connectSlotsByName(frmSeleccionColor)

    def retranslateUi(self, frmSeleccionColor):
        _translate = QtCore.QCoreApplication.translate
        frmSeleccionColor.setWindowTitle(_translate("frmSeleccionColor", "Selección de Colores"))
        self.btnSeleccionColor.setText(_translate("frmSeleccionColor", "Seleccionar color..."))
        self.lblColor.setText(_translate("frmSeleccionColor", "Color Seleccionado (Hex):"))
