# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizadorImagen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmVisualizaImagen(object):
    def setupUi(self, frmVisualizaImagen):
        frmVisualizaImagen.setObjectName("frmVisualizaImagen")
        frmVisualizaImagen.resize(640, 480)
        self.gpcImagen = QtWidgets.QGraphicsView(frmVisualizaImagen)
        self.gpcImagen.setGeometry(QtCore.QRect(10, 10, 621, 461))
        self.gpcImagen.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.gpcImagen.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gpcImagen.setObjectName("gpcImagen")

        self.retranslateUi(frmVisualizaImagen)
        QtCore.QMetaObject.connectSlotsByName(frmVisualizaImagen)

    def retranslateUi(self, frmVisualizaImagen):
        _translate = QtCore.QCoreApplication.translate
        frmVisualizaImagen.setWindowTitle(_translate("frmVisualizaImagen", "Visualizador de imágenes"))
