# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeleccionFuentes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmSeleccionFuentes(object):
    def setupUi(self, frmSeleccionFuentes):
        frmSeleccionFuentes.setObjectName("frmSeleccionFuentes")
        frmSeleccionFuentes.resize(320, 240)
        self.txteTexto = QtWidgets.QTextEdit(frmSeleccionFuentes)
        self.txteTexto.setGeometry(QtCore.QRect(10, 70, 301, 161))
        self.txteTexto.setObjectName("txteTexto")
        self.btnSeleccionFuente = QtWidgets.QPushButton(frmSeleccionFuentes)
        self.btnSeleccionFuente.setGeometry(QtCore.QRect(100, 20, 130, 23))
        self.btnSeleccionFuente.setObjectName("btnSeleccionFuente")

        self.retranslateUi(frmSeleccionFuentes)
        QtCore.QMetaObject.connectSlotsByName(frmSeleccionFuentes)

    def retranslateUi(self, frmSeleccionFuentes):
        _translate = QtCore.QCoreApplication.translate
        frmSeleccionFuentes.setWindowTitle(_translate("frmSeleccionFuentes", "Selección de Fuentes"))
        self.btnSeleccionFuente.setText(_translate("frmSeleccionFuentes", "Seleccionar fuente..."))
