# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaFlotante.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class venPrincipal(object):
    def setupUi(self, venPrincipal):
        venPrincipal.setObjectName("venPrincipal")
        venPrincipal.resize(550, 461)
        self.centralwidget = QtWidgets.QWidget(venPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        venPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(venPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        venPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(venPrincipal)
        self.statusbar.setObjectName("statusbar")
        venPrincipal.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(venPrincipal)
        self.dockWidget.setMinimumSize(QtCore.QSize(350, 200))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.lblTitulo = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblTitulo.setGeometry(QtCore.QRect(130, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.formLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 50, 311, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblUsuario = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblUsuario.setObjectName("lblUsuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUsuario)
        self.txtUsuario = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtUsuario.setObjectName("txtUsuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUsuario)
        self.lblPass = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblPass.setObjectName("lblPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblPass)
        self.txtPass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPass.setObjectName("txtPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPass)
        self.btnIniciarSesion = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnIniciarSesion.setObjectName("btnIniciarSesion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnIniciarSesion)
        self.dockWidget.setWidget(self.dockWidgetContents)
        venPrincipal.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(venPrincipal)
        QtCore.QMetaObject.connectSlotsByName(venPrincipal)

    def retranslateUi(self, venPrincipal):
        _translate = QtCore.QCoreApplication.translate
        venPrincipal.setWindowTitle(_translate("venPrincipal", "Ventana Principal"))
        self.menuArchivo.setTitle(_translate("venPrincipal", "Archivo"))
        self.dockWidget.setWindowTitle(_translate("venPrincipal", "Inicio de sesión"))
        self.lblTitulo.setText(_translate("venPrincipal", "Inicio de Sesión"))
        self.lblUsuario.setText(_translate("venPrincipal", "Usuario:"))
        self.lblPass.setText(_translate("venPrincipal", "Contraseña:"))
        self.btnIniciarSesion.setText(_translate("venPrincipal", "Iniciar Sesion"))
