# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pizzeria.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmPrincipal(object):
    def setupUi(self, frmPrincipal):
        frmPrincipal.setObjectName("frmPrincipal")
        frmPrincipal.resize(220, 222)
        self.lblPrecioBase = QtWidgets.QLabel(frmPrincipal)
        self.lblPrecioBase.setGeometry(QtCore.QRect(20, 20, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPrecioBase.setFont(font)
        self.lblPrecioBase.setObjectName("lblPrecioBase")
        self.lblResultado = QtWidgets.QLabel(frmPrincipal)
        self.lblResultado.setGeometry(QtCore.QRect(20, 180, 200, 16))
        self.lblResultado.setObjectName("lblResultado")
        self.lblExtras = QtWidgets.QLabel(frmPrincipal)
        self.lblExtras.setGeometry(QtCore.QRect(20, 50, 101, 16))
        self.lblExtras.setObjectName("lblExtras")
        self.verticalLayoutWidget = QtWidgets.QWidget(frmPrincipal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlyExtras = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlyExtras.setContentsMargins(0, 0, 0, 0)
        self.vlyExtras.setObjectName("vlyExtras")
        self.chkQueso = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkQueso.setObjectName("chkQueso")
        self.vlyExtras.addWidget(self.chkQueso)
        self.chkJamon = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkJamon.setObjectName("chkJamon")
        self.vlyExtras.addWidget(self.chkJamon)
        self.chkChampinon = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkChampinon.setObjectName("chkChampinon")
        self.vlyExtras.addWidget(self.chkChampinon)

        self.retranslateUi(frmPrincipal)
        QtCore.QMetaObject.connectSlotsByName(frmPrincipal)

    def retranslateUi(self, frmPrincipal):
        _translate = QtCore.QCoreApplication.translate
        frmPrincipal.setWindowTitle(_translate("frmPrincipal", "Pizzeria"))
        self.lblPrecioBase.setText(_translate("frmPrincipal", "Precio Base Pizza: 15 €"))
        self.lblResultado.setText(_translate("frmPrincipal", "<<Muestra el coste total>>"))
        self.lblExtras.setText(_translate("frmPrincipal", "Seleccionar extras:"))
        self.chkQueso.setText(_translate("frmPrincipal", "Extra Queso"))
        self.chkJamon.setText(_translate("frmPrincipal", "Jamón York"))
        self.chkChampinon.setText(_translate("frmPrincipal", "Champiñones"))
