# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmChat(object):
    def setupUi(self, frmChat):
        frmChat.setObjectName("frmChat")
        frmChat.resize(812, 502)
        self.widget = QtWidgets.QWidget(frmChat)
        self.widget.setGeometry(QtCore.QRect(20, 20, 771, 461))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtTexto = QtWidgets.QLineEdit(self.widget)
        self.txtTexto.setObjectName("txtTexto")
        self.gridLayout.addWidget(self.txtTexto, 2, 0, 1, 1)
        self.btnEnviar = QtWidgets.QPushButton(self.widget)
        self.btnEnviar.setObjectName("btnEnviar")
        self.gridLayout.addWidget(self.btnEnviar, 2, 1, 1, 1)
        self.lblTitulo = QtWidgets.QLabel(self.widget)
        self.lblTitulo.setText("")
        self.lblTitulo.setObjectName("lblTitulo")
        self.gridLayout.addWidget(self.lblTitulo, 0, 0, 1, 1)
        self.txteChat = QtWidgets.QTextEdit(self.widget)
        self.txteChat.setObjectName("txteChat")
        self.gridLayout.addWidget(self.txteChat, 1, 0, 1, 2)

        self.retranslateUi(frmChat)
        QtCore.QMetaObject.connectSlotsByName(frmChat)
        frmChat.setTabOrder(self.txtTexto, self.btnEnviar)
        frmChat.setTabOrder(self.btnEnviar, self.txteChat)

    def retranslateUi(self, frmChat):
        _translate = QtCore.QCoreApplication.translate
        frmChat.setWindowTitle(_translate("frmChat", "Conversación Cliente-Servidor"))
        self.btnEnviar.setText(_translate("frmChat", "Enviar"))
