# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class fonsiApp(object):
    def setupUi(self, fonsiApp):
        fonsiApp.setObjectName("fonsiApp")
        fonsiApp.resize(1021, 519)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fonsiApp.sizePolicy().hasHeightForWidth())
        fonsiApp.setSizePolicy(sizePolicy)
        #fonsiApp.setMinimumSize(QtCore.QSize(1021, 519))
        #fonsiApp.setMaximumSize(QtCore.QSize(1021, 519))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono_principal.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fonsiApp.setWindowIcon(icon)
        fonsiApp.setAutoFillBackground(True)
        fonsiApp.setStyleSheet("QLineEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #5e90fa;\n"
"    border-radius: 3px;\n"
"}")
        fonsiApp.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(fonsiApp)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        #self.label.setGeometry(QtCore.QRect(0, 0, 1131, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("fondo.jpg"))
        self.label.setObjectName("label")
        fonsiApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fonsiApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Ficheros = QtWidgets.QMenu(self.menubar)
        self.menu_Ficheros.setObjectName("menu_Ficheros")
        self.menuFichas = QtWidgets.QMenu(self.menu_Ficheros)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/ficha.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuFichas.setIcon(icon1)
        self.menuFichas.setObjectName("menuFichas")
        self.menuSocios = QtWidgets.QMenu(self.menu_Ficheros)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSocios.setIcon(icon2)
        self.menuSocios.setObjectName("menuSocios")
        fonsiApp.setMenuBar(self.menubar)
        self.actionClientes = QtWidgets.QAction(fonsiApp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/iconos/clientes.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes.setIcon(icon3)
        self.actionClientes.setObjectName("actionClientes")
        self.actionEmpresas = QtWidgets.QAction(fonsiApp)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconos/iconos/empresas.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmpresas.setIcon(icon4)
        self.actionEmpresas.setObjectName("actionEmpresas")
        self.actionCuotas_de_Socios = QtWidgets.QAction(fonsiApp)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconos/iconos/euros.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCuotas_de_Socios.setIcon(icon5)
        self.actionCuotas_de_Socios.setObjectName("actionCuotas_de_Socios")
        self.actionSocio = QtWidgets.QAction(fonsiApp)
        self.actionSocio.setIcon(icon2)
        self.actionSocio.setObjectName("actionSocio")
        self.actionIniciar_Sesi_n = QtWidgets.QAction(fonsiApp)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconos/iconos/iniciar_sesion.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIniciar_Sesi_n.setIcon(icon6)
        self.actionIniciar_Sesi_n.setObjectName("actionIniciar_Sesi_n")
        self.actionSalir = QtWidgets.QAction(fonsiApp)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconos/iconos/salir.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon7)
        self.actionSalir.setObjectName("actionSalir")
        self.menuFichas.addAction(self.actionClientes)
        self.menuFichas.addAction(self.actionEmpresas)
        self.menuSocios.addAction(self.actionCuotas_de_Socios)
        self.menuSocios.addAction(self.actionSocio)
        self.menu_Ficheros.addAction(self.menuFichas.menuAction())
        self.menu_Ficheros.addAction(self.menuSocios.menuAction())
        self.menu_Ficheros.addSeparator()
        self.menu_Ficheros.addAction(self.actionIniciar_Sesi_n)
        self.menu_Ficheros.addSeparator()
        self.menu_Ficheros.addAction(self.actionSalir)
        self.menubar.addAction(self.menu_Ficheros.menuAction())

        self.retranslateUi(fonsiApp)
        QtCore.QMetaObject.connectSlotsByName(fonsiApp)

    def retranslateUi(self, fonsiApp):
        _translate = QtCore.QCoreApplication.translate
        fonsiApp.setWindowTitle(_translate("fonsiApp", "AM Sport - Menú Principal"))
        self.menu_Ficheros.setTitle(_translate("fonsiApp", "&Ficheros"))
        self.menuFichas.setTitle(_translate("fonsiApp", "Fichas"))
        self.menuSocios.setTitle(_translate("fonsiApp", "Socios"))
        self.actionClientes.setText(_translate("fonsiApp", "Clientes"))
        self.actionClientes.setShortcut(_translate("fonsiApp", "Shift+C"))
        self.actionEmpresas.setText(_translate("fonsiApp", "Empresas"))
        self.actionCuotas_de_Socios.setText(_translate("fonsiApp", "Cuotas de Socios"))
        self.actionSocio.setText(_translate("fonsiApp", "Socios"))
        self.actionIniciar_Sesi_n.setText(_translate("fonsiApp", "Iniciar Sesión"))
        self.actionSalir.setText(_translate("fonsiApp", "Salir"))
import imagenes
