# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisorLCD.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmVisorLCD(object):
    def setupUi(self, frmVisorLCD):
        frmVisorLCD.setObjectName("frmVisorLCD")
        frmVisorLCD.resize(311, 152)
        self.lcdNumero = QtWidgets.QLCDNumber(frmVisorLCD)
        self.lcdNumero.setGeometry(QtCore.QRect(20, 20, 271, 71))
        self.lcdNumero.setSmallDecimalPoint(False)
        self.lcdNumero.setObjectName("lcdNumero")
        self.btnDecimal = QtWidgets.QPushButton(frmVisorLCD)
        self.btnDecimal.setGeometry(QtCore.QRect(20, 110, 61, 23))
        self.btnDecimal.setObjectName("btnDecimal")
        self.btnBinario = QtWidgets.QPushButton(frmVisorLCD)
        self.btnBinario.setGeometry(QtCore.QRect(90, 110, 61, 23))
        self.btnBinario.setObjectName("btnBinario")
        self.btnOctal = QtWidgets.QPushButton(frmVisorLCD)
        self.btnOctal.setGeometry(QtCore.QRect(160, 110, 61, 23))
        self.btnOctal.setObjectName("btnOctal")
        self.btnHexadecimal = QtWidgets.QPushButton(frmVisorLCD)
        self.btnHexadecimal.setGeometry(QtCore.QRect(230, 110, 61, 23))
        self.btnHexadecimal.setObjectName("btnHexadecimal")

        self.retranslateUi(frmVisorLCD)
        QtCore.QMetaObject.connectSlotsByName(frmVisorLCD)

    def retranslateUi(self, frmVisorLCD):
        _translate = QtCore.QCoreApplication.translate
        frmVisorLCD.setWindowTitle(_translate("frmVisorLCD", "Visor LCD"))
        self.btnDecimal.setText(_translate("frmVisorLCD", "Decimal"))
        self.btnBinario.setText(_translate("frmVisorLCD", "Binario"))
        self.btnOctal.setText(_translate("frmVisorLCD", "Octal"))
        self.btnHexadecimal.setText(_translate("frmVisorLCD", "Hexadec."))
