# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentaCamisas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentaCamisas(object):
    def setupUi(self, frmVenta):
        frmVenta.setObjectName("frmVenta")
        frmVenta.resize(341, 369)
        self.lblTallas = QtWidgets.QLabel(frmVenta)
        self.lblTallas.setGeometry(QtCore.QRect(30, 20, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTallas.setFont(font)
        self.lblTallas.setObjectName("lblTallas")
        self.lblPagos = QtWidgets.QLabel(frmVenta)
        self.lblPagos.setGeometry(QtCore.QRect(30, 180, 181, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPagos.setFont(font)
        self.lblPagos.setObjectName("lblPagos")
        self.lblResultado = QtWidgets.QLabel(frmVenta)
        self.lblResultado.setGeometry(QtCore.QRect(30, 330, 281, 16))
        self.lblResultado.setObjectName("lblResultado")
        self.verticalLayoutWidget = QtWidgets.QWidget(frmVenta)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 201, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlyTalla = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlyTalla.setContentsMargins(0, 0, 0, 0)
        self.vlyTalla.setObjectName("vlyTalla")
        self.rbtTallaM = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtTallaM.setObjectName("rbtTallaM")
        self.vlyTalla.addWidget(self.rbtTallaM)
        self.rbtTallaL = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtTallaL.setObjectName("rbtTallaL")
        self.vlyTalla.addWidget(self.rbtTallaL)
        self.rbtTallaXL = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtTallaXL.setObjectName("rbtTallaXL")
        self.vlyTalla.addWidget(self.rbtTallaXL)
        self.rbtTallaXXL = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtTallaXXL.setObjectName("rbtTallaXXL")
        self.vlyTalla.addWidget(self.rbtTallaXXL)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(frmVenta)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 220, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vlyPago = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlyPago.setContentsMargins(0, 0, 0, 0)
        self.vlyPago.setObjectName("vlyPago")
        self.rbtPagoTarjeta = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbtPagoTarjeta.setObjectName("rbtPagoTarjeta")
        self.vlyPago.addWidget(self.rbtPagoTarjeta)
        self.rbtPagoContra = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbtPagoContra.setObjectName("rbtPagoContra")
        self.vlyPago.addWidget(self.rbtPagoContra)
        self.rbtPagoTransferencia = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbtPagoTransferencia.setObjectName("rbtPagoTransferencia")
        self.vlyPago.addWidget(self.rbtPagoTransferencia)

        self.retranslateUi(frmVenta)
        QtCore.QMetaObject.connectSlotsByName(frmVenta)

    def retranslateUi(self, frmVenta):
        _translate = QtCore.QCoreApplication.translate
        frmVenta.setWindowTitle(_translate("frmVenta", "Venta"))
        self.lblTallas.setText(_translate("frmVenta", "Escoja la talla de su camisa: "))
        self.lblPagos.setText(_translate("frmVenta", "Seleccione su método de pago:"))
        self.lblResultado.setText(_translate("frmVenta", "<<Muestra talla y método de pago>>"))
        self.rbtTallaM.setText(_translate("frmVenta", "M"))
        self.rbtTallaL.setText(_translate("frmVenta", "L"))
        self.rbtTallaXL.setText(_translate("frmVenta", "XL"))
        self.rbtTallaXXL.setText(_translate("frmVenta", "XXL"))
        self.rbtPagoTarjeta.setText(_translate("frmVenta", "Tarjeta Débito/Crédito"))
        self.rbtPagoContra.setText(_translate("frmVenta", "Pago Contrareembolso"))
        self.rbtPagoTransferencia.setText(_translate("frmVenta", "Trasferencia Bancaria"))
