# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificarContrasena.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmModificarContrasena(object):
    def setupUi(self, frmModificarContrasena):
        frmModificarContrasena.setObjectName("frmModificarContrasena")
        frmModificarContrasena.resize(380, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/candado.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmModificarContrasena.setWindowIcon(icon)
        frmModificarContrasena.setStyleSheet("QPushButton#btnModificar, #btnCancelar {\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"    border: 1px solid #828282;\n"
"    padding: 5px 12px 5px 12px;\n"
"    margin: 4px 8px 4px 8px;\n"
"    border-radius: 3px;\n"
"    min-width: 14px;\n"
"    min-height: 14px;\n"
"}\n"
"\n"
"QPushButton#btnModificar:hover, #btnModificar:focus{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #2eae35, stop:1 #cae44a);\n"
"}\n"
"\n"
"QPushButton#btnCancelar:hover, #btnCancelar:focus{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #95050d, stop:1 #ea0a20);\n"
"}\n"
"\n"
"\n"
"QPushButton#btnModificar:pressed {\n"
"    background-color: #2eae35;\n"
"}\n"
"\n"
"QPushButton#btnCancelar:pressed {\n"
"    background-color: #95050d;\n"
"}\n"
"\n"
"QPushButton#btnValidaUsuario, #btnValidaContrasena, #btnValidaNuevaContrasena{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #5e90fa;\n"
"    border-radius: 3px;\n"
"\n"
"}")
        self.formLayoutWidget = QtWidgets.QWidget(frmModificarContrasena)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 311, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formUsuario = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formUsuario.setContentsMargins(0, 0, 0, 0)
        self.formUsuario.setObjectName("formUsuario")
        self.lblUsuario = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setObjectName("lblUsuario")
        self.formUsuario.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUsuario)
        self.txtUsuario = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtUsuario.setObjectName("txtUsuario")
        self.formUsuario.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUsuario)
        self.lblContrasena = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblContrasena.setFont(font)
        self.lblContrasena.setObjectName("lblContrasena")
        self.formUsuario.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblContrasena)
        self.txtContrasena = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtContrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContrasena.setObjectName("txtContrasena")
        self.formUsuario.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtContrasena)
        self.lblNuevaContrasena = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNuevaContrasena.setFont(font)
        self.lblNuevaContrasena.setObjectName("lblNuevaContrasena")
        self.formUsuario.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblNuevaContrasena)
        self.txtNuevaContrasena = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtNuevaContrasena.setObjectName("txtNuevaContrasena")
        self.formUsuario.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtNuevaContrasena)
        self.lblTitulo = QtWidgets.QLabel(frmModificarContrasena)
        self.lblTitulo.setGeometry(QtCore.QRect(108, 12, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.btnModificar = QtWidgets.QPushButton(frmModificarContrasena)
        self.btnModificar.setGeometry(QtCore.QRect(120, 150, 121, 34))
        self.btnModificar.setStyleSheet("")
        self.btnModificar.setIconSize(QtCore.QSize(16, 16))
        self.btnModificar.setObjectName("btnModificar")
        self.btnCancelar = QtWidgets.QPushButton(frmModificarContrasena)
        self.btnCancelar.setGeometry(QtCore.QRect(228, 150, 121, 34))
        self.btnCancelar.setIconSize(QtCore.QSize(32, 32))
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnValidaUsuario = QtWidgets.QPushButton(frmModificarContrasena)
        self.btnValidaUsuario.setGeometry(QtCore.QRect(350, 60, 21, 20))
        self.btnValidaUsuario.setText("")
        self.btnValidaUsuario.setObjectName("btnValidaUsuario")
        self.btnValidaContrasena = QtWidgets.QPushButton(frmModificarContrasena)
        self.btnValidaContrasena.setGeometry(QtCore.QRect(350, 85, 21, 20))
        self.btnValidaContrasena.setText("")
        self.btnValidaContrasena.setObjectName("btnValidaContrasena")
        self.btnValidaNuevaContrasena = QtWidgets.QPushButton(frmModificarContrasena)
        self.btnValidaNuevaContrasena.setGeometry(QtCore.QRect(350, 113, 21, 20))
        self.btnValidaNuevaContrasena.setText("")
        self.btnValidaNuevaContrasena.setObjectName("btnValidaNuevaContrasena")

        self.retranslateUi(frmModificarContrasena)
        QtCore.QMetaObject.connectSlotsByName(frmModificarContrasena)
        frmModificarContrasena.setTabOrder(self.txtUsuario, self.txtContrasena)
        frmModificarContrasena.setTabOrder(self.txtContrasena, self.txtNuevaContrasena)
        frmModificarContrasena.setTabOrder(self.txtNuevaContrasena, self.btnModificar)
        frmModificarContrasena.setTabOrder(self.btnModificar, self.btnCancelar)
        frmModificarContrasena.setTabOrder(self.btnCancelar, self.btnValidaUsuario)
        frmModificarContrasena.setTabOrder(self.btnValidaUsuario, self.btnValidaNuevaContrasena)
        frmModificarContrasena.setTabOrder(self.btnValidaNuevaContrasena, self.btnValidaContrasena)

    def retranslateUi(self, frmModificarContrasena):
        _translate = QtCore.QCoreApplication.translate
        frmModificarContrasena.setWindowTitle(_translate("frmModificarContrasena", "Modificar Contraseña"))
        self.lblUsuario.setText(_translate("frmModificarContrasena", "Usuario:"))
        self.lblContrasena.setText(_translate("frmModificarContrasena", "Anterior Contraseña:"))
        self.lblNuevaContrasena.setText(_translate("frmModificarContrasena", "Nueva Contraseña:"))
        self.lblTitulo.setText(_translate("frmModificarContrasena", "Modificar Contraseña"))
        self.btnModificar.setText(_translate("frmModificarContrasena", "Modificar"))
        self.btnCancelar.setText(_translate("frmModificarContrasena", "Cancelar"))
import imagenes
