# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NivelSalud.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmNiveles(object):
    def setupUi(self, frmNiveles):
        frmNiveles.setObjectName("frmNiveles")
        frmNiveles.resize(471, 371)
        self.lblAzucar = QtWidgets.QLabel(frmNiveles)
        self.lblAzucar.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAzucar.setFont(font)
        self.lblAzucar.setObjectName("lblAzucar")
        self.sbhAzucar = QtWidgets.QScrollBar(frmNiveles)
        self.sbhAzucar.setGeometry(QtCore.QRect(130, 20, 311, 20))
        self.sbhAzucar.setOrientation(QtCore.Qt.Horizontal)
        self.sbhAzucar.setObjectName("sbhAzucar")
        self.lblPresion = QtWidgets.QLabel(frmNiveles)
        self.lblPresion.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPresion.setFont(font)
        self.lblPresion.setObjectName("lblPresion")
        self.slhPresion = QtWidgets.QSlider(frmNiveles)
        self.slhPresion.setGeometry(QtCore.QRect(130, 70, 311, 22))
        self.slhPresion.setOrientation(QtCore.Qt.Horizontal)
        self.slhPresion.setObjectName("slhPresion")
        self.lblPulso = QtWidgets.QLabel(frmNiveles)
        self.lblPulso.setGeometry(QtCore.QRect(20, 120, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPulso.setFont(font)
        self.lblPulso.setObjectName("lblPulso")
        self.sbvPulso = QtWidgets.QScrollBar(frmNiveles)
        self.sbvPulso.setGeometry(QtCore.QRect(130, 120, 16, 160))
        self.sbvPulso.setOrientation(QtCore.Qt.Vertical)
        self.sbvPulso.setObjectName("sbvPulso")
        self.lblColesterol = QtWidgets.QLabel(frmNiveles)
        self.lblColesterol.setGeometry(QtCore.QRect(210, 120, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblColesterol.setFont(font)
        self.lblColesterol.setObjectName("lblColesterol")
        self.slvColesterol = QtWidgets.QSlider(frmNiveles)
        self.slvColesterol.setGeometry(QtCore.QRect(350, 120, 22, 160))
        self.slvColesterol.setOrientation(QtCore.Qt.Vertical)
        self.slvColesterol.setObjectName("slvColesterol")
        self.txtResultado = QtWidgets.QLineEdit(frmNiveles)
        self.txtResultado.setGeometry(QtCore.QRect(30, 320, 411, 20))
        self.txtResultado.setReadOnly(True)
        self.txtResultado.setObjectName("txtResultado")

        self.retranslateUi(frmNiveles)
        QtCore.QMetaObject.connectSlotsByName(frmNiveles)

    def retranslateUi(self, frmNiveles):
        _translate = QtCore.QCoreApplication.translate
        frmNiveles.setWindowTitle(_translate("frmNiveles", "Niveles de Salud"))
        self.lblAzucar.setText(_translate("frmNiveles", "Nivel de azucar:"))
        self.lblPresion.setText(_translate("frmNiveles", "Presión alterial:"))
        self.lblPulso.setText(_translate("frmNiveles", "Pulso:"))
        self.lblColesterol.setText(_translate("frmNiveles", "Nivel de Colesterol:"))
