# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmCalculadora(object):
    def setupUi(self, frmCalculadora):
        frmCalculadora.setObjectName("frmCalculadora")
        frmCalculadora.resize(432, 183)
        self.lblNum1 = QtWidgets.QLabel(frmCalculadora)
        self.lblNum1.setGeometry(QtCore.QRect(20, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNum1.setFont(font)
        self.lblNum1.setObjectName("lblNum1")
        self.lblNum2 = QtWidgets.QLabel(frmCalculadora)
        self.lblNum2.setGeometry(QtCore.QRect(20, 70, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNum2.setFont(font)
        self.lblNum2.setObjectName("lblNum2")
        self.txtNum1 = QtWidgets.QLineEdit(frmCalculadora)
        self.txtNum1.setGeometry(QtCore.QRect(170, 30, 113, 20))
        self.txtNum1.setObjectName("txtNum1")
        self.txtNum2 = QtWidgets.QLineEdit(frmCalculadora)
        self.txtNum2.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.txtNum2.setObjectName("txtNum2")
        self.lblResultado = QtWidgets.QLabel(frmCalculadora)
        self.lblResultado.setGeometry(QtCore.QRect(20, 130, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblResultado.setFont(font)
        self.lblResultado.setObjectName("lblResultado")
        self.txtResultado = QtWidgets.QLineEdit(frmCalculadora)
        self.txtResultado.setGeometry(QtCore.QRect(170, 130, 113, 20))
        self.txtResultado.setObjectName("txtResultado")
        self.btnSumar = QtWidgets.QPushButton(frmCalculadora)
        self.btnSumar.setGeometry(QtCore.QRect(320, 30, 75, 23))
        self.btnSumar.setObjectName("btnSumar")
        self.btnRestar = QtWidgets.QPushButton(frmCalculadora)
        self.btnRestar.setGeometry(QtCore.QRect(320, 60, 75, 23))
        self.btnRestar.setObjectName("btnRestar")
        self.btnMultiplicar = QtWidgets.QPushButton(frmCalculadora)
        self.btnMultiplicar.setGeometry(QtCore.QRect(320, 90, 75, 23))
        self.btnMultiplicar.setObjectName("btnMultiplicar")
        self.btnDividir = QtWidgets.QPushButton(frmCalculadora)
        self.btnDividir.setGeometry(QtCore.QRect(320, 120, 75, 23))
        self.btnDividir.setObjectName("btnDividir")
        self.grbOperaciones = QtWidgets.QGroupBox(frmCalculadora)
        self.grbOperaciones.setGeometry(QtCore.QRect(300, 10, 111, 151))
        self.grbOperaciones.setObjectName("grbOperaciones")
        self.grbOperaciones.raise_()
        self.lblNum1.raise_()
        self.lblNum2.raise_()
        self.txtNum1.raise_()
        self.txtNum2.raise_()
        self.lblResultado.raise_()
        self.txtResultado.raise_()
        self.btnSumar.raise_()
        self.btnRestar.raise_()
        self.btnMultiplicar.raise_()
        self.btnDividir.raise_()

        self.retranslateUi(frmCalculadora)
        QtCore.QMetaObject.connectSlotsByName(frmCalculadora)

    def retranslateUi(self, frmCalculadora):
        _translate = QtCore.QCoreApplication.translate
        frmCalculadora.setWindowTitle(_translate("frmCalculadora", "Calculadora"))
        self.lblNum1.setText(_translate("frmCalculadora", "Ingrese primer número:"))
        self.lblNum2.setText(_translate("frmCalculadora", "Ingrese segundo número:"))
        self.lblResultado.setText(_translate("frmCalculadora", "Resultado:"))
        self.btnSumar.setText(_translate("frmCalculadora", "+"))
        self.btnRestar.setText(_translate("frmCalculadora", "-"))
        self.btnMultiplicar.setText(_translate("frmCalculadora", "X"))
        self.btnDividir.setText(_translate("frmCalculadora", "/"))
        self.grbOperaciones.setTitle(_translate("frmCalculadora", "Operaciones"))
