# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Diagnosticos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmDiagnostico(object):
    def setupUi(self, frmDiagnostico):
        frmDiagnostico.setObjectName("frmDiagnostico")
        frmDiagnostico.resize(400, 263)
        self.lblDiagnosticos = QtWidgets.QLabel(frmDiagnostico)
        self.lblDiagnosticos.setGeometry(QtCore.QRect(20, 20, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDiagnosticos.setFont(font)
        self.lblDiagnosticos.setObjectName("lblDiagnosticos")
        self.lblDiagnosSelec = QtWidgets.QLabel(frmDiagnostico)
        self.lblDiagnosSelec.setGeometry(QtCore.QRect(20, 140, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDiagnosSelec.setFont(font)
        self.lblDiagnosSelec.setObjectName("lblDiagnosSelec")
        self.listDiagnosticos = QtWidgets.QListWidget(frmDiagnostico)
        self.listDiagnosticos.setGeometry(QtCore.QRect(190, 20, 191, 101))
        self.listDiagnosticos.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listDiagnosticos.setObjectName("listDiagnosticos")
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listDiagnosticos.addItem(item)
        self.listDiagnosSelec = QtWidgets.QListWidget(frmDiagnostico)
        self.listDiagnosSelec.setGeometry(QtCore.QRect(190, 140, 191, 101))
        self.listDiagnosSelec.setObjectName("listDiagnosSelec")

        self.retranslateUi(frmDiagnostico)
        QtCore.QMetaObject.connectSlotsByName(frmDiagnostico)

    def retranslateUi(self, frmDiagnostico):
        _translate = QtCore.QCoreApplication.translate
        frmDiagnostico.setWindowTitle(_translate("frmDiagnostico", "Diagnósticos"))
        self.lblDiagnosticos.setText(_translate("frmDiagnostico", "Seleccione los diagnósticos:"))
        self.lblDiagnosSelec.setText(_translate("frmDiagnostico", "Diagnósticos selecionados:"))
        __sortingEnabled = self.listDiagnosticos.isSortingEnabled()
        self.listDiagnosticos.setSortingEnabled(False)
        item = self.listDiagnosticos.item(0)
        item.setText(_translate("frmDiagnostico", "Rayos X: 5 €"))
        item = self.listDiagnosticos.item(1)
        item.setText(_translate("frmDiagnostico", "Nivel de Azucar: 3 €"))
        item = self.listDiagnosticos.item(2)
        item.setText(_translate("frmDiagnostico", "Prueba de Hemoglobina: 7 €"))
        item = self.listDiagnosticos.item(3)
        item.setText(_translate("frmDiagnostico", "Análisis de Orina: 8 €"))
        item = self.listDiagnosticos.item(4)
        item.setText(_translate("frmDiagnostico", "Análisis de Sangre: 10 €"))
        self.listDiagnosticos.setSortingEnabled(__sortingEnabled)
