# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectorFuentes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmFuentes(object):
    def setupUi(self, frmFuentes):
        frmFuentes.setObjectName("frmFuentes")
        frmFuentes.resize(410, 241)
        self.lblSeleccionFuente = QtWidgets.QLabel(frmFuentes)
        self.lblSeleccionFuente.setGeometry(QtCore.QRect(30, 30, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSeleccionFuente.setFont(font)
        self.lblSeleccionFuente.setObjectName("lblSeleccionFuente")
        self.fcmbFuentes = QtWidgets.QFontComboBox(frmFuentes)
        self.fcmbFuentes.setGeometry(QtCore.QRect(140, 30, 231, 22))
        self.fcmbFuentes.setObjectName("fcmbFuentes")
        self.lblFuente = QtWidgets.QLabel(frmFuentes)
        self.lblFuente.setGeometry(QtCore.QRect(30, 70, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFuente.setFont(font)
        self.lblFuente.setObjectName("lblFuente")
        self.txteFuentes = QtWidgets.QTextEdit(frmFuentes)
        self.txteFuentes.setGeometry(QtCore.QRect(140, 70, 231, 141))
        self.txteFuentes.setObjectName("txteFuentes")

        self.retranslateUi(frmFuentes)
        QtCore.QMetaObject.connectSlotsByName(frmFuentes)

    def retranslateUi(self, frmFuentes):
        _translate = QtCore.QCoreApplication.translate
        frmFuentes.setWindowTitle(_translate("frmFuentes", "Selector de Fuentes"))
        self.lblSeleccionFuente.setText(_translate("frmFuentes", "Seleccione Fuente:"))
        self.lblFuente.setText(_translate("frmFuentes", "Editor de texto:"))
