# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TablaLenguajes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmTabla(object):
    def setupUi(self, frmTabla):
        frmTabla.setObjectName("frmTabla")
        frmTabla.resize(431, 290)
        self.tabLenguajes = QtWidgets.QTableWidget(frmTabla)
        self.tabLenguajes.setGeometry(QtCore.QRect(10, 10, 411, 271))
        self.tabLenguajes.setObjectName("tabLenguajes")
        self.tabLenguajes.setColumnCount(2)
        self.tabLenguajes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabLenguajes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabLenguajes.setHorizontalHeaderItem(1, item)

        self.retranslateUi(frmTabla)
        QtCore.QMetaObject.connectSlotsByName(frmTabla)

    def retranslateUi(self, frmTabla):
        _translate = QtCore.QCoreApplication.translate
        frmTabla.setWindowTitle(_translate("frmTabla", "Tabla Lenguajes Programación"))
        item = self.tabLenguajes.horizontalHeaderItem(0)
        item.setText(_translate("frmTabla", "Lenguaje"))
        item = self.tabLenguajes.horizontalHeaderItem(1)
        item.setText(_translate("frmTabla", "Versión"))
