# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestorDescargas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmGestorDescarga(object):
    def setupUi(self, frmGestorDescarga):
        frmGestorDescarga.setObjectName("frmGestorDescarga")
        frmGestorDescarga.resize(320, 151)
        self.lblTitulo = QtWidgets.QLabel(frmGestorDescarga)
        self.lblTitulo.setGeometry(QtCore.QRect(90, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.btnIniciarDescarga = QtWidgets.QPushButton(frmGestorDescarga)
        self.btnIniciarDescarga.setGeometry(QtCore.QRect(90, 100, 121, 23))
        self.btnIniciarDescarga.setObjectName("btnIniciarDescarga")
        self.pgbDescargaArchivo = QtWidgets.QProgressBar(frmGestorDescarga)
        self.pgbDescargaArchivo.setGeometry(QtCore.QRect(40, 60, 241, 16))
        self.pgbDescargaArchivo.setProperty("value", 0)
        self.pgbDescargaArchivo.setObjectName("pgbDescargaArchivo")

        self.retranslateUi(frmGestorDescarga)
        QtCore.QMetaObject.connectSlotsByName(frmGestorDescarga)

    def retranslateUi(self, frmGestorDescarga):
        _translate = QtCore.QCoreApplication.translate
        frmGestorDescarga.setWindowTitle(_translate("frmGestorDescarga", "Gestor de descargas"))
        self.lblTitulo.setText(_translate("frmGestorDescarga", "Descarga de archivos"))
        self.btnIniciarDescarga.setText(_translate("frmGestorDescarga", "Iniciar la descarga"))
