# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BarraHerramientas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmBarraHerramientas(object):
    def setupUi(self, frmBarraHerramientas):
        frmBarraHerramientas.setObjectName("frmBarraHerramientas")
        frmBarraHerramientas.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(frmBarraHerramientas)
        self.centralwidget.setObjectName("centralwidget")
        frmBarraHerramientas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(frmBarraHerramientas)
        self.statusbar.setObjectName("statusbar")
        frmBarraHerramientas.setStatusBar(self.statusbar)
        self.barraMenu = QtWidgets.QToolBar(frmBarraHerramientas)
        self.barraMenu.setMovable(False)
        self.barraMenu.setOrientation(QtCore.Qt.Horizontal)
        self.barraMenu.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.barraMenu.setObjectName("barraMenu")
        frmBarraHerramientas.addToolBar(QtCore.Qt.TopToolBarArea, self.barraMenu)
        self.mniNuevo = QtWidgets.QAction(frmBarraHerramientas)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconosBarra/iconos/añadir.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mniNuevo.setIcon(icon)
        self.mniNuevo.setObjectName("mniNuevo")
        self.mniBuscar = QtWidgets.QAction(frmBarraHerramientas)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconosBarra/iconos/buscar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mniBuscar.setIcon(icon1)
        self.mniBuscar.setObjectName("mniBuscar")
        self.mniEliminar = QtWidgets.QAction(frmBarraHerramientas)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconosBarra/iconos/borrar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mniEliminar.setIcon(icon2)
        self.mniEliminar.setObjectName("mniEliminar")
        self.barraMenu.addAction(self.mniNuevo)
        self.barraMenu.addAction(self.mniBuscar)
        self.barraMenu.addAction(self.mniEliminar)

        self.retranslateUi(frmBarraHerramientas)
        QtCore.QMetaObject.connectSlotsByName(frmBarraHerramientas)

    def retranslateUi(self, frmBarraHerramientas):
        _translate = QtCore.QCoreApplication.translate
        frmBarraHerramientas.setWindowTitle(_translate("frmBarraHerramientas", "Barra de Herramientas"))
        self.barraMenu.setWindowTitle(_translate("frmBarraHerramientas", "toolBar"))
        self.mniNuevo.setText(_translate("frmBarraHerramientas", "Nuevo"))
        self.mniNuevo.setToolTip(_translate("frmBarraHerramientas", "Crea un usuario"))
        self.mniNuevo.setShortcut(_translate("frmBarraHerramientas", "Shift+N"))
        self.mniBuscar.setText(_translate("frmBarraHerramientas", "Buscar"))
        self.mniBuscar.setToolTip(_translate("frmBarraHerramientas", "Buscar un usuario"))
        self.mniBuscar.setShortcut(_translate("frmBarraHerramientas", "Shift+M"))
        self.mniEliminar.setText(_translate("frmBarraHerramientas", "Eliminar"))
        self.mniEliminar.setToolTip(_translate("frmBarraHerramientas", "Elimina un usuario"))
        self.mniEliminar.setShortcut(_translate("frmBarraHerramientas", "Shift+E"))
import recurso
