# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EliminarUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmEliminarUsuario(object):
    def setupUi(self, frmEliminarUsuario):
        frmEliminarUsuario.setObjectName("frmEliminarUsuario")
        frmEliminarUsuario.resize(311, 173)
        frmEliminarUsuario.setStyleSheet("QDialog{\n"
"background-image: url(:/imagenes/fondo.PNG);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton#btnAceptar, #btnCancelar {\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"    border: 1px solid #828282;\n"
"    padding: 5px 12px 5px 12px;\n"
"    margin: 4px 8px 4px 8px;\n"
"    border-radius: 3px;\n"
"    min-width: 14px;\n"
"    min-height: 14px;\n"
"}\n"
"\n"
"QPushButton#btnAceptar:hover, #btnAceptar:focus{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #2eae35, stop:1 #cae44a);\n"
"}\n"
"\n"
"QPushButton#btnCancelar:hover, #btnCancelar:focus{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #95050d, stop:1 #ea0a20);\n"
"}\n"
"\n"
"QPushButton#btnAceptar:pressed {\n"
"    background-color: #2eae35;\n"
"}\n"
"\n"
"QPushButton#btnCancelar:pressed {\n"
"    background-color: #95050d;\n"
"}\n"
"\n"
"QPushButton#btnValidaUsuario, #btnValidaContrasena{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #5e90fa;\n"
"    border-radius: 3px;\n"
"\n"
"}")
        self.formLayoutWidget = QtWidgets.QWidget(frmEliminarUsuario)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 251, 64))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formUsuario = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formUsuario.setContentsMargins(0, 0, 0, 0)
        self.formUsuario.setObjectName("formUsuario")
        self.lblUsuario = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setObjectName("lblUsuario")
        self.formUsuario.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUsuario)
        self.txtUsuario = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtUsuario.setObjectName("txtUsuario")
        self.formUsuario.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUsuario)
        self.lblContrasena = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblContrasena.setFont(font)
        self.lblContrasena.setObjectName("lblContrasena")
        self.formUsuario.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblContrasena)
        self.txtContrasena = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtContrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContrasena.setObjectName("txtContrasena")
        self.formUsuario.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtContrasena)
        self.lblTitulo = QtWidgets.QLabel(frmEliminarUsuario)
        self.lblTitulo.setGeometry(QtCore.QRect(46, 12, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.btnAceptar = QtWidgets.QPushButton(frmEliminarUsuario)
        self.btnAceptar.setGeometry(QtCore.QRect(60, 124, 121, 34))
        self.btnAceptar.setStyleSheet("")
        self.btnAceptar.setIconSize(QtCore.QSize(16, 16))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCancelar = QtWidgets.QPushButton(frmEliminarUsuario)
        self.btnCancelar.setGeometry(QtCore.QRect(168, 124, 121, 34))
        self.btnCancelar.setIconSize(QtCore.QSize(32, 32))
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnValidaUsuario = QtWidgets.QPushButton(frmEliminarUsuario)
        self.btnValidaUsuario.setGeometry(QtCore.QRect(284, 60, 21, 20))
        self.btnValidaUsuario.setText("")
        self.btnValidaUsuario.setObjectName("btnValidaUsuario")
        self.btnValidaContrasena = QtWidgets.QPushButton(frmEliminarUsuario)
        self.btnValidaContrasena.setGeometry(QtCore.QRect(284, 85, 21, 20))
        self.btnValidaContrasena.setText("")
        self.btnValidaContrasena.setObjectName("btnValidaContrasena")

        self.retranslateUi(frmEliminarUsuario)
        QtCore.QMetaObject.connectSlotsByName(frmEliminarUsuario)
        frmEliminarUsuario.setTabOrder(self.txtUsuario, self.txtContrasena)
        frmEliminarUsuario.setTabOrder(self.txtContrasena, self.btnAceptar)
        frmEliminarUsuario.setTabOrder(self.btnAceptar, self.btnCancelar)

    def retranslateUi(self, frmEliminarUsuario):
        _translate = QtCore.QCoreApplication.translate
        frmEliminarUsuario.setWindowTitle(_translate("frmEliminarUsuario", "Eliminar Usuario"))
        self.lblUsuario.setText(_translate("frmEliminarUsuario", "Usuario:"))
        self.lblContrasena.setText(_translate("frmEliminarUsuario", "Contraseña:"))
        self.lblTitulo.setText(_translate("frmEliminarUsuario", "Eliminar cuenta de usuario"))
        self.btnAceptar.setText(_translate("frmEliminarUsuario", "Eliminar Usuario"))
        self.btnCancelar.setText(_translate("frmEliminarUsuario", "Cancelar"))

import imagenes
