# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsertarRegistros.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmInsertarRegistros(object):
    def setupUi(self, frmInsertarRegistros):
        frmInsertarRegistros.setObjectName("frmInsertarRegistros")
#        frmInsertarRegistros.resize(342, 232)
        self.lblBBDD = QtWidgets.QLabel(frmInsertarRegistros)
        self.lblBBDD.setGeometry(QtCore.QRect(20, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBBDD.setFont(font)
        self.lblBBDD.setObjectName("lblBBDD")
        self.lblTabla = QtWidgets.QLabel(frmInsertarRegistros)
        self.lblTabla.setGeometry(QtCore.QRect(20, 102, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTabla.setFont(font)
        self.lblTabla.setObjectName("lblTabla")
        self.lblCodigo = QtWidgets.QLabel(frmInsertarRegistros)
        self.lblCodigo.setGeometry(QtCore.QRect(20, 133, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCodigo.setFont(font)
        self.lblCodigo.setObjectName("lblCodigo")
        self.lblNombre = QtWidgets.QLabel(frmInsertarRegistros)
        self.lblNombre.setGeometry(QtCore.QRect(20, 163, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName("lblNombre")
        self.txtBBDD = QtWidgets.QLineEdit(frmInsertarRegistros)
        self.txtBBDD.setGeometry(QtCore.QRect(110, 30, 211, 20))
        self.txtBBDD.setObjectName("txtBBDD")
        self.txtTabla = QtWidgets.QLineEdit(frmInsertarRegistros)
        self.txtTabla.setGeometry(QtCore.QRect(80, 100, 241, 20))
        self.txtTabla.setObjectName("txtTabla")
        self.txtCodigo = QtWidgets.QLineEdit(frmInsertarRegistros)
        self.txtCodigo.setGeometry(QtCore.QRect(80, 130, 241, 20))
        self.txtCodigo.setObjectName("txtCodigo")
        self.txtNombre = QtWidgets.QLineEdit(frmInsertarRegistros)
        self.txtNombre.setGeometry(QtCore.QRect(80, 160, 241, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.btnConectar = QtWidgets.QPushButton(frmInsertarRegistros)
        self.btnConectar.setGeometry(QtCore.QRect(160, 60, 161, 23))
        self.btnConectar.setWhatsThis("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("conectar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConectar.setIcon(icon)
        self.btnConectar.setObjectName("btnConectar")
        self.btnInsertar = QtWidgets.QPushButton(frmInsertarRegistros)
        self.btnInsertar.setGeometry(QtCore.QRect(161, 190, 161, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("insertar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInsertar.setIcon(icon1)
        self.btnInsertar.setObjectName("btnInsetar")

        self.retranslateUi(frmInsertarRegistros)
        QtCore.QMetaObject.connectSlotsByName(frmInsertarRegistros)
        frmInsertarRegistros.setTabOrder(self.txtBBDD, self.btnConectar)
        frmInsertarRegistros.setTabOrder(self.btnConectar, self.txtTabla)
        frmInsertarRegistros.setTabOrder(self.txtTabla, self.txtCodigo)
        frmInsertarRegistros.setTabOrder(self.txtCodigo, self.txtNombre)
        frmInsertarRegistros.setTabOrder(self.txtNombre, self.btnInsertar)

    def retranslateUi(self, frmInsertarRegistros):
        _translate = QtCore.QCoreApplication.translate
        frmInsertarRegistros.setWindowTitle(_translate("frmInsertarRegistros", "Inserción de registros"))
        self.lblBBDD.setText(_translate("frmInsertarRegistros", "Base de datos:"))
        self.lblTabla.setText(_translate("frmInsertarRegistros", "Tabla:"))
        self.lblCodigo.setText(_translate("frmInsertarRegistros", "Código:"))
        self.lblNombre.setText(_translate("frmInsertarRegistros", "Nombre:"))
        self.txtTabla.setPlaceholderText(_translate("frmInsertarRegistros", "Nombre de tabla"))
        self.txtCodigo.setPlaceholderText(_translate("frmInsertarRegistros", "Código"))
        self.txtNombre.setPlaceholderText(_translate("frmInsertarRegistros", "Nombre"))
        self.btnConectar.setToolTip(_translate("frmInsertarRegistros", "Conectar a la BBDD"))
        self.btnConectar.setText(_translate("frmInsertarRegistros", "Conectar"))
        self.btnInsertar.setToolTip(_translate("frmInsertarRegistros", "Insertar nuevo registro"))
        self.btnInsertar.setText(_translate("frmInsertarRegistros", "Insertar Registro"))
