# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorTexto.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class vntEditorTexto(object):
    def setupUi(self, vntEditorTexto):
        vntEditorTexto.setObjectName("vntEditorTexto")
        vntEditorTexto.resize(519, 409)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vntEditorTexto.sizePolicy().hasHeightForWidth())
        vntEditorTexto.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(vntEditorTexto)
        self.centralwidget.setObjectName("centralwidget")
        self.txteTexto = QtWidgets.QTextEdit(self.centralwidget)
        self.txteTexto.setGeometry(QtCore.QRect(-1, 10, 521, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txteTexto.sizePolicy().hasHeightForWidth())
        self.txteTexto.setSizePolicy(sizePolicy)
        self.txteTexto.setObjectName("txteTexto")
        vntEditorTexto.setCentralWidget(self.centralwidget)
        self.mbrMenu = QtWidgets.QMenuBar(vntEditorTexto)
        self.mbrMenu.setGeometry(QtCore.QRect(0, 0, 519, 21))
        self.mbrMenu.setObjectName("mbrMenu")
        self.menArchivo = QtWidgets.QMenu(self.mbrMenu)
        self.menArchivo.setObjectName("menArchivo")
        vntEditorTexto.setMenuBar(self.mbrMenu)
        self.statusbar = QtWidgets.QStatusBar(vntEditorTexto)
        self.statusbar.setObjectName("statusbar")
        vntEditorTexto.setStatusBar(self.statusbar)
        self.mniAbrir = QtWidgets.QAction(vntEditorTexto)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iconos/abrir.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mniAbrir.setIcon(icon)
        self.mniAbrir.setObjectName("mniAbrir")
        self.mniGuardar = QtWidgets.QAction(vntEditorTexto)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Iconos/guardar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mniGuardar.setIcon(icon1)
        self.mniGuardar.setObjectName("mniGuardar")
        self.mniSalir = QtWidgets.QAction(vntEditorTexto)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Iconos/salir.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mniSalir.setIcon(icon2)
        self.mniSalir.setObjectName("mniSalir")
        self.menArchivo.addAction(self.mniAbrir)
        self.menArchivo.addAction(self.mniGuardar)
        self.menArchivo.addSeparator()
        self.menArchivo.addAction(self.mniSalir)
        self.mbrMenu.addAction(self.menArchivo.menuAction())

        self.retranslateUi(vntEditorTexto)
        QtCore.QMetaObject.connectSlotsByName(vntEditorTexto)

    def retranslateUi(self, vntEditorTexto):
        _translate = QtCore.QCoreApplication.translate
        vntEditorTexto.setWindowTitle(_translate("vntEditorTexto", "Editor Texto"))
        self.menArchivo.setTitle(_translate("vntEditorTexto", "Archivo"))
        self.mniAbrir.setText(_translate("vntEditorTexto", "Abrir..."))
        self.mniAbrir.setShortcut(_translate("vntEditorTexto", "Ctrl+T"))
        self.mniGuardar.setText(_translate("vntEditorTexto", "Guardar..."))
        self.mniGuardar.setShortcut(_translate("vntEditorTexto", "Ctrl+G"))
        self.mniSalir.setText(_translate("vntEditorTexto", "Salir"))
        self.mniSalir.setShortcut(_translate("vntEditorTexto", "Ctrl+S"))
