# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lenguajes_programacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmLenguajes(object):
    def setupUi(self, frmLenguajes):
        frmLenguajes.setObjectName("frmLenguajes")
        frmLenguajes.resize(441, 123)
        self.lblLenguaje = QtWidgets.QLabel(frmLenguajes)
        self.lblLenguaje.setGeometry(QtCore.QRect(20, 20, 221, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLenguaje.setFont(font)
        self.lblLenguaje.setObjectName("lblLenguaje")
        self.cmbLenguaje = QtWidgets.QComboBox(frmLenguajes)
        self.cmbLenguaje.setGeometry(QtCore.QRect(260, 20, 161, 22))
        self.cmbLenguaje.setObjectName("cmbLenguaje")
        self.cmbLenguaje.addItem("")
        self.cmbLenguaje.addItem("")
        self.cmbLenguaje.addItem("")
        self.cmbLenguaje.addItem("")
        self.cmbLenguaje.addItem("")
        self.cmbLenguaje.addItem("")
        self.cmbLenguaje.addItem("")
        self.lblLenguajeSelec = QtWidgets.QLabel(frmLenguajes)
        self.lblLenguajeSelec.setGeometry(QtCore.QRect(20, 80, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLenguajeSelec.setFont(font)
        self.lblLenguajeSelec.setObjectName("lblLenguajeSelec")
        self.txtLenguajeSel = QtWidgets.QLineEdit(frmLenguajes)
        self.txtLenguajeSel.setGeometry(QtCore.QRect(260, 80, 161, 20))
        self.txtLenguajeSel.setObjectName("txtLenguajeSel")

        self.retranslateUi(frmLenguajes)
        self.cmbLenguaje.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmLenguajes)

    def retranslateUi(self, frmLenguajes):
        _translate = QtCore.QCoreApplication.translate
        frmLenguajes.setWindowTitle(_translate("frmLenguajes", "Lenguajes de Programación"))
        self.lblLenguaje.setText(_translate("frmLenguajes", "Seleccione lenguaje de programación:"))
        self.cmbLenguaje.setItemText(0, _translate("frmLenguajes", "Python"))
        self.cmbLenguaje.setItemText(1, _translate("frmLenguajes", "Java"))
        self.cmbLenguaje.setItemText(2, _translate("frmLenguajes", "C#"))
        self.cmbLenguaje.setItemText(3, _translate("frmLenguajes", "PHP"))
        self.cmbLenguaje.setItemText(4, _translate("frmLenguajes", "JavaScript"))
        self.cmbLenguaje.setItemText(5, _translate("frmLenguajes", "C++"))
        self.cmbLenguaje.setItemText(6, _translate("frmLenguajes", "SQL"))
        self.lblLenguajeSelec.setText(_translate("frmLenguajes", "Lenguaje de programación seleccionado:"))
