# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmCalendario(object):
    def setupUi(self, frmCalendario):
        frmCalendario.setObjectName("frmCalendario")
        frmCalendario.resize(360, 262)
        self.calCalendario = QtWidgets.QCalendarWidget(frmCalendario)
        self.calCalendario.setGeometry(QtCore.QRect(20, 20, 321, 183))
        self.calCalendario.setObjectName("calCalendario")
        self.dateFecha = QtWidgets.QDateEdit(frmCalendario)
        self.dateFecha.setGeometry(QtCore.QRect(100, 220, 161, 22))
        self.dateFecha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateFecha.setObjectName("dateFecha")

        self.retranslateUi(frmCalendario)
        QtCore.QMetaObject.connectSlotsByName(frmCalendario)

    def retranslateUi(self, frmCalendario):
        _translate = QtCore.QCoreApplication.translate
        frmCalendario.setWindowTitle(_translate("frmCalendario", "Calendario"))
