# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoSaludo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoSaludar(object):
    def setupUi(self, DialogoSaludar):
        DialogoSaludar.setObjectName("DialogoSaludar")
        DialogoSaludar.resize(320, 140)
        self.lblNombre = QtWidgets.QLabel(DialogoSaludar)
        self.lblNombre.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.lblNombre.setObjectName("lblNombre")
        self.lblSaludar = QtWidgets.QLabel(DialogoSaludar)
        self.lblSaludar.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.lblSaludar.setObjectName("lblSaludar")
        self.txtNombre = QtWidgets.QLineEdit(DialogoSaludar)
        self.txtNombre.setGeometry(QtCore.QRect(120, 20, 181, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.lblMensajeSaludo = QtWidgets.QLabel(DialogoSaludar)
        self.lblMensajeSaludo.setGeometry(QtCore.QRect(120, 60, 181, 16))
        self.lblMensajeSaludo.setText("")
        self.lblMensajeSaludo.setObjectName("lblMensajeSaludo")
        self.btnSaludar = QtWidgets.QPushButton(DialogoSaludar)
        self.btnSaludar.setGeometry(QtCore.QRect(120, 90, 181, 23))
        self.btnSaludar.setObjectName("btnSaludar")

        self.retranslateUi(DialogoSaludar)
        QtCore.QMetaObject.connectSlotsByName(DialogoSaludar)

    def retranslateUi(self, DialogoSaludar):
        _translate = QtCore.QCoreApplication.translate
        DialogoSaludar.setWindowTitle(_translate("DialogoSaludar", "Saludo"))
        self.lblNombre.setText(_translate("DialogoSaludar", "Escriba su nombre:"))
        self.lblSaludar.setText(_translate("DialogoSaludar", "Saludo:"))
        self.btnSaludar.setText(_translate("DialogoSaludar", "Saludar"))
