# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeleccionPais.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class frmPais(object):
    def setupUi(self, frmPais):
        frmPais.setObjectName("frmPais")
        frmPais.resize(402, 82)
        self.lblPais = QtWidgets.QLabel(frmPais)
        self.lblPais.setGeometry(QtCore.QRect(20, 30, 47, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPais.setFont(font)
        self.lblPais.setObjectName("lblPais")
        self.txtPais = QtWidgets.QLineEdit(frmPais)
        self.txtPais.setGeometry(QtCore.QRect(70, 30, 181, 20))
        self.txtPais.setReadOnly(True)
        self.txtPais.setObjectName("txtPais")
        self.btnSeleccionPais = QtWidgets.QPushButton(frmPais)
        self.btnSeleccionPais.setGeometry(QtCore.QRect(260, 29, 120, 23))
        self.btnSeleccionPais.setObjectName("btnSeleccionPais")

        self.retranslateUi(frmPais)
        QtCore.QMetaObject.connectSlotsByName(frmPais)

    def retranslateUi(self, frmPais):
        _translate = QtCore.QCoreApplication.translate
        frmPais.setWindowTitle(_translate("frmPais", "Selección de País"))
        self.lblPais.setText(_translate("frmPais", "Su país:"))
        self.btnSeleccionPais.setText(_translate("frmPais", "Seleccionar País"))
